# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#Sitemap
gems:
  - jekyll-sitemap
  

# Site settings
title: awen.io
description: The personal website for Awen Saunders
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://awen.io" # the base hostname & protocol for your site
github_username: "awensaunders"
twitter_username: "awen_saunders"

# Build settings
markdown: kramdown
